### ISSUE TITLE
Firmware + Interrupts

### ISSUE THREAD

**Issue by mrmolex** [sparkfun/Blynk_Board_ESP8266#5]
Hi!.  The digital pins can handle interrupts? in which pins? what limitations have?.  NOTE: i need to count a pulse signal with a max. frequency of 2 Hz.

**Comment by bboyho** [comment]
Hi,

This case looks stale and does not seem to be an issue with the Blynk board or core firmware. However, I can answer a few of your questions:

If you are still wondering, [all the ESP8266's digital pins can handle interrupts except for GPIO16](https://arduino-esp8266.readthedocs.io/en/2.6.3/reference.html#digital-io). When using the ESP8266 community's board definition (v2.5.1 and above) for the ESP8266, you must include `ICACHE_RAM_ATTR` before the function definition. For additional limitations, check out the [reference guide for the ESP8266](https://arduino-esp8266.readthedocs.io/en/2.6.3/reference.html#interrupts) . In terms of the ESP8266 and the Blynk app, the minimum update rate is 1 second. I have not tried this before but you could [manually set the rate](https://docs.blynk.cc/#blynk-main-operations-get-data-from-hardware-pushing-data-from-hardware) for anything less than a second using the PUSH option.
